name: Python Coverage

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  python-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      